Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "rmq01" do |n|
    n.vm.hostname = "rmq01"
    n.vm.network "private_network", ip: "192.168.56.10"

    n.vm.provider "virtualbox" do |vb|
      vb.name = "rmq01"
      vb.memory = 2048
      vb.cpus = 2
    end

    n.vm.provision "shell", path: "provision.sh"
  end
end

